// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Flat {
	
	
	public partial class index {
		
		protected System.Web.UI.HtmlControls.HtmlHead Head1;
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected FlatButton.Controls.FlatButton Mark;
		
		protected FlatButton.Controls.FlatButton Check;
		
		protected FlatButton.Controls.FlatButton Check0;
		
		protected FlatButton.Controls.FlatButton Check1;
	}
}
